sudo: required
language: java

services:
- docker
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t dejankovacevic/github-bot:latest . ;
      docker push dejankovacevic/github-bot ;
    fi
