sudo: required
language: java

services:
- docker

notifications:
  webhooks:
      - http://services.wire.com/github/travis/163bf4f9-8b06-43fc-ab46-472ae2d602be

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t $DOCKER_USERNAME/github-bot:latest . ;
      docker push $DOCKER_USERNAME/github-bot ;
    fi

